#' Generates a comparison plot within risk quantiles
#'
#' Generates a plot with relative and absolute risk reductions. It can handle one or multiple outcomes. In the case of multiple outcomes the input must be a named list.
#'
#' @param dataARR A list or dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{absoluteRiskReduction}}
#' @param dataRRR A list or dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{relativeRiskReduction}}
#' @param ylimRRR The limits on the y-axis of the hazard ratio plot
#' @param ylimARR The limits on the y-axis of the sbsolute risk reduction plot
#' @param legend.position The position of the legend in the plot
#' @param position_dodge.w The amount of space between bullets in the ploit in the case of multiple outcomes
#'
#' @return A plot with hazard ratios and absolute risk reductions across risk strata
#'
#' @export

comparisonPlot <- function(dataARR,
                           dataRRR,
                           ylimARR,
                           ylimRRR,
                           legend.position = c(.15, .1),
                           position_dodge.w = .2){



  if(is.data.frame(dataARR))
    legend.position <- 'none'
  dataARRCombined <- dplyr::bind_rows(dataARR, .id = 'outcome')
  dataRRRCombined <- dplyr::bind_rows(dataRRR, .id = 'outcome')
  dataARRCombined$riskStratum <- factor(paste0('Q', dataARRCombined$riskStratum))
  dataRRRCombined$riskStratum <- factor(paste0('Q', dataRRRCombined$riskStratum))

  HRPlot <- ggplot2::ggplot(dataRRRCombined, ggplot2::aes(x = riskStratum,
                                                          y = HR,
                                                          group = outcome,
                                                          color = outcome)) +
    ggplot2::geom_point(ggplot2::aes(color  = outcome, shape = outcome),
                        size = 3,
                        position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95),
                           width = .2,
                           position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 1, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Hazard Ratio') +
    ggplot2::coord_cartesian(ylim = ylimRRR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.position = legend.position,
                   legend.title = ggplot2::element_blank(),
                   legend.text = ggplot2::element_text(face = 'bold'))

  ARRPlot <- ggplot2::ggplot(dataARRCombined, ggplot2::aes(x = riskStratum,
                                                           y = ARR,
                                                           group = outcome,
                                                           color = outcome)) +
    ggplot2::geom_point(ggplot2::aes(color= outcome, shape = outcome),
                        size = 3,
                        position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95),
                           width = .2,
                           position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 0, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Absolute Risk Reduction') +
    ggplot2::coord_cartesian(ylim = ylimARR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.title = ggplot2::element_blank(),
                   legend.position = 'none',
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank())
  grid::grid.newpage()
  grid::grid.draw(rbind(ggplot2::ggplotGrob(ARRPlot), ggplot2::ggplotGrob(HRPlot), size = "first"))

}
