#' Generates a comparison plot within risk quantiles
#'
#' Generates a plot with hazard ratios and absolute risk reductions along with confidence intervals
#'
#' @param dataARR A dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{absoluteRiskReductionDataFrame}}
#' @param dataHR A dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{hazardRatioDataFrame}}
#' @param position_dodge.w The position dodge in the graph
#' @param legend.position The position of the legend in the graph
#' @param ylimHR The limits on the y-axis of the hazard ratio plot
#' @param ylimARR The limits on the y-axis of the sbsolute risk reduction plot
#'
#' @return A plot with hazard ratios and absolute risk reductions across risk strata
#'
#' @export

comparisonPlotGeneral <- function(dataARR,
                                  dataHR,
                                  position_dodge.w = .2,
                                  legend.position = c(.15, .1),
                                  ylimHR = c(0, 5),
                                  ylimARR  =c(-1, 1)){

  dataARR$riskStratum <- factor(paste0('Q', dataARR$riskStratum))
  dataHR$riskStratum <- factor(paste0('Q', dataHR$riskStratum))

  HRPlot <- ggplot2::ggplot(dataHR, ggplot2::aes(x = riskStratum, y = HR, group = riskModel, color =riskModel)) +
    ggplot2::geom_point(ggplot2::aes(color  = riskModel, shape = riskModel), size = 3, position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95), width = .2, position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 1, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Hazard Ratio') +
    ggplot2::coord_cartesian(ylim = ylimHR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.title = ggplot2::element_blank(),
                   legend.position = legend.position)

  ARRPlot <- ggplot2::ggplot(dataARR, ggplot2::aes(x = riskStratum, y = ARR, group = riskModel, color =riskModel)) +
    ggplot2::geom_point(ggplot2::aes(color  = riskModel, shape = riskModel), size = 3, position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95), width = .2, position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 0, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Absolute Risk Reduction') +
    ggplot2::coord_cartesian(ylim = ylimARR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.title = ggplot2::element_blank(),
                   legend.position = 'none',
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank())

  grid::grid.draw(rbind(ggplot2::ggplotGrob(ARRPlot), ggplot2::ggplotGrob(HRPlot), size = "first"))

}


