#' Generates a comparison plot within risk quantiles
#'
#' Generates a plot with relative and absolute risk reductions. It can handle one or multiple outcomes. In the case of multiple outcomes the input must be a named list.
#'
#' @param dataARR A list or dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{absoluteRiskReduction}}
#' @param dataRRR A list or dataframe same as the one generated by \code{\link[RiskStratifiedEstimation]{relativeRiskReduction}}
#' @param cases The dataframe or list with the outcome rates within risk strata. In the case of multiple outcomes the names of the list will be used as outcome labels
#' @param treatmentLabel The name of the treatment drug
#' @param comparatorLabel The name of the comparator drug
#' @param ylimRRR The limits on the y-axis of the hazard ratio plot
#' @param ylimARR The limits on the y-axis of the sbsolute risk reduction plot
#' @param ylimCases The limits on the y-axis of the outcome rates bar plot
#' @param position_dodge.w The amount of space between bullets in the ploit in the case of multiple outcomes
#'
#' @return A plot with hazard ratios and absolute risk reductions across risk strata
#'
#' @export

comparisonPlot <- function(dataARR,
                           dataRRR,
                           cases,
                           treatmentLabel,
                           comparatorLabel,
                           ylimARR,
                           ylimRRR,
                           ylimCases = c(0, 1),
                           position_dodge.w = .2){




  if(!missing(treatmentLabel) & !missing(comparatorLabel)){
    k <- length(cases)
    for(i in 1:k){
      cases[[i]]$cohort <- ifelse(cases[[i]]$cohort == 'comparator', comparatorLabel, treatmentLabel)
    }

  }

  dataARRCombined <- dplyr::bind_rows(dataARR, .id = 'outcome')
  dataRRRCombined <- dplyr::bind_rows(dataRRR, .id = 'outcome')
  casesCombined <- dplyr::bind_rows(cases, .id = 'outcome')
  casesCombined <- tidyr::unite(casesCombined, col = outcomeCohort, 'outcome', 'cohort')
  dataARRCombined$riskStratum <- factor(paste0('Q', dataARRCombined$riskStratum))
  dataRRRCombined$riskStratum <- factor(paste0('Q', dataRRRCombined$riskStratum))


  casesPlot <- ggplot2::ggplot(data = casesCombined, ggplot2::aes(x = riskStratum, y = outcomeRate)) +
    ggplot2::geom_bar(stat = 'identity', position = ggplot2::position_dodge(), ggplot2::aes(fill =outcomeCohort), width = .5)+
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Outcome Rate') +
    ggplot2::geom_hline(yintercept = 0, size = .8) +
    ggplot2::coord_cartesian(ylim = ylimCases) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.title = ggplot2::element_blank(),
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   legend.direction = 'horizontal',
                   legend.position = 'top') + ggplot2::scale_y_reverse()

  if(is.data.frame(dataARR)){
    legendPositionRisk <- 'none'
  } else{
    legendPositionRisk <- 'bottom'
  }


  HRPlot <- ggplot2::ggplot(dataRRRCombined, ggplot2::aes(x = riskStratum,
                                                          y = HR,
                                                          group = outcome,
                                                          color = outcome)) +
    ggplot2::geom_point(ggplot2::aes(color  = outcome, shape = outcome),
                        size = 3,
                        position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95),
                           width = 0,
                           position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 1, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Hazard Ratio') +
    ggplot2::coord_cartesian(ylim = ylimRRR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.title = ggplot2::element_blank(),
                   legend.position = 'none',
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank())


  ARRPlot <- ggplot2::ggplot(dataARRCombined, ggplot2::aes(x = riskStratum,
                                                           y = ARR,
                                                           group = outcome,
                                                           color = outcome)) +
    ggplot2::geom_point(ggplot2::aes(color= outcome, shape = outcome),
                        size = 3,
                        position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lower95, ymax = upper95),
                           width = 0,
                           position = ggplot2::position_dodge(w = position_dodge.w)) +
    ggplot2::geom_hline(yintercept = 0, linetype = 'dashed', size = .8) +
    ggplot2::xlab('Risk Stratum') +
    ggplot2::ylab('Absolute \n Risk Reduction') +
    ggplot2::coord_cartesian(ylim = ylimARR) +
    ggplot2::theme_minimal() +
    ggplot2::theme(legend.direction = 'horizontal',
                   legend.position = 'bottom',
                   legend.title = ggplot2::element_blank())
  grid::grid.newpage()
  riskPlots <- grid::grid.draw(rbind(ggplot2::ggplotGrob(casesPlot), ggplot2::ggplotGrob(HRPlot), ggplot2::ggplotGrob(ARRPlot), size = "last"))

}
